update intellij support to  2022.*
knoxfighter/intellij-factorio-autocompletion pull request #12
Opened 2022-08-12 14:53 UTC by serieznyi

2022-08-13 06:29 UTC, serieznyi commented on build.gradle
> -    changeNotes """
Now changelog generating to `plugin.xml` from `Changelog.md` by `changelog` plugin

2022-08-13 06:31 UTC, serieznyi commented on src/main/resources/META-INF/plugin.xml
> -    <idea-version since-build="202.5103.13" until-build="212.*"/>
Filled  by `intellij.patchPluginXml`

2022-08-13 10:54 UTC, knoxfighter requested changes

2022-08-13 10:54 UTC, knoxfighter commented on src/main/java/moe/knox/factorio/parser/FactorioPrototypeParser.java
>  import org.jsoup.safety.Whitelist;
remove deprecated import

2022-08-13 10:54 UTC, knoxfighter commented on build.gradle
> +sourceCompatibility = 17
Using `public static final [JavaVersion](https://docs.gradle.org/current/javadoc/org/gradle/api/JavaVersion.html) VERSION_17` instead of the direct number?

2022-08-13 10:54 UTC, knoxfighter commented on build.gradle
> +    version = "1.0.0"
1.0.0 is not the current version. Also this field should be not needed.
From [documentation](https://github.com/JetBrains/gradle-changelog-plugin#configuration):
> Current version. By default, global project's version is used.

2022-08-13 10:54 UTC, knoxfighter commented on build.gradle
> +    path = "${project.projectDir}/Changelog.md"
This is the default path, so not needed to set this.

2022-08-13 14:37 UTC, serieznyi commented on build.gradle
> +    version = "1.0.0"
I thought this is version of changelog specification. Ok. I remove it

2022-08-13 18:35 UTC, serieznyi commented on build.gradle
> +    path = "${project.projectDir}/Changelog.md"
Default path use `CHANGELOG.md` instead `Changelog.md`

2022-08-14 15:59 UTC, serieznyi commented on src/main/java/moe/knox/factorio/parser/FactorioPrototypeParser.java
>  import org.jsoup.safety.Whitelist;
remove

2022-08-14 15:59 UTC, serieznyi commented on build.gradle
> +sourceCompatibility = 17
used enum

2022-08-14 15:59 UTC, serieznyi commented on build.gradle
> +    version = "1.0.0"
removed

2022-08-14 16:02 UTC, serieznyi commented on build.gradle
> +    changeNotes = getPluginChangelog()
I little broke view of plugin changelog then start use changelog plugin, so I rewrite it. 
I use template like in EmmyLua. What you think?

![изображение](https://user-images.githubusercontent.com/2323142/184545244-625d8e47-c2e8-4ddc-b941-6a5afac42294.png)

2022-08-14 16:22 UTC, knoxfighter approved these changes

2022-08-14 16:24 UTC, merged