Rewrite factorio api version logic
knoxfighter/intellij-factorio-autocompletion pull request #22
Opened 2022-09-05 04:50 UTC by serieznyi

- In business logic we use `FactorioApiVersion` class that encapsulate real api version
 - In config we use presentation of version class (`DropdownVersion`) that cant be named as latest
 - Versions parsing moved in own class + add test
 - Set minimal supported version of api

2022-09-11 13:45 UTC, knoxfighter requested changes
Sort the config in the options in reverse order, so the latest version number is directly below the `latest` tag.

When setting the option to `Latest version` and then clicking on ok or reload integration, an error pops up `Error getting current tag. Lualib not downloaded`.

On first startup i had the crash.
```
java.lang.NullPointerException: Cannot invoke "org.jsoup.nodes.Element.text()" because the return value of "org.jsoup.nodes.Document.selectFirst(String)" is null
	at moe.knox.factorio.core.parser.ApiParser.downloadAndParseAPI(ApiParser.java:687)
	at moe.knox.factorio.core.parser.ApiParser.assureDir(ApiParser.java:653)
	at moe.knox.factorio.core.parser.ApiParser.run(ApiParser.java:127)
	at com.intellij.openapi.progress.impl.CoreProgressManager.startTask(CoreProgressManager.java:442)
	at com.intellij.openapi.progress.impl.ProgressManagerImpl.startTask(ProgressManagerImpl.java:114)
	at com.intellij.openapi.progress.impl.CoreProgressManager.lambda$runProcessWithProgressAsynchronously$5(CoreProgressManager.java:493)
	at com.intellij.openapi.progress.impl.ProgressRunner.lambda$submit$3(ProgressRunner.java:252)
	at com.intellij.openapi.progress.impl.CoreProgressManager.lambda$runProcess$2(CoreProgressManager.java:188)
	at com.intellij.openapi.progress.impl.CoreProgressManager.lambda$executeProcessUnderProgress$12(CoreProgressManager.java:608)
	at com.intellij.openapi.progress.impl.CoreProgressManager.registerIndicatorAndRun(CoreProgressManager.java:683)
	at com.intellij.openapi.progress.impl.CoreProgressManager.computeUnderProgress(CoreProgressManager.java:639)
	at com.intellij.openapi.progress.impl.CoreProgressManager.executeProcessUnderProgress(CoreProgressManager.java:607)
	at com.intellij.openapi.progress.impl.ProgressManagerImpl.executeProcessUnderProgress(ProgressManagerImpl.java:60)
	at com.intellij.openapi.progress.impl.CoreProgressManager.runProcess(CoreProgressManager.java:175)
	at com.intellij.openapi.progress.impl.ProgressRunner.lambda$submit$4(ProgressRunner.java:252)
	at java.base/java.util.concurrent.CompletableFuture$AsyncSupply.run(CompletableFuture.java:1768)
	at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1136)
	at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:635)
	at java.base/java.util.concurrent.Executors$PrivilegedThreadFactory$1$1.run(Executors.java:702)
	at java.base/java.util.concurrent.Executors$PrivilegedThreadFactory$1$1.run(Executors.java:699)
	at java.base/java.security.AccessController.doPrivileged(AccessController.java:399)
	at java.base/java.util.concurrent.Executors$PrivilegedThreadFactory$1.run(Executors.java:699)
	at java.base/java.lang.Thread.run(Thread.java:833)
```
To reproduce:
Select any version and download it, then restart the IDE.

Also i would recommend to also save `latest` as state, so on every startup it is checked if a new version is available and then automatically downloaded (and not only manually).

2022-09-11 13:45 UTC, knoxfighter commented on src/main/java/moe/knox/factorio/core/parser/ApiParser.java
> +    private static FactorioApiVersion detectNewestAllowedVersion(Project project)
use `latest` instead of `newest`

2022-09-11 13:45 UTC, knoxfighter commented on src/main/java/moe/knox/factorio/core/version/ApiVersionResolver.java
> +    final private SemVer minimalSupportedVersion = new SemVer("1.1.62", 1, 1, 62);
Earliest supported version should be 1.1.35?

2022-09-11 14:46 UTC, serieznyi commented on src/main/java/moe/knox/factorio/core/version/ApiVersionResolver.java
> +    final private SemVer minimalSupportedVersion = new SemVer("1.1.62", 1, 1, 62);
1.1.35 - first version with JSON API supporting
1.1.62 -  since 1.1.62 developers remove type `variant` and maybe they change more api stuffs.

If you want - I can set 1.1.35 as minimal version in current PR, but later we must set more newest version.

2022-09-11 15:04 UTC, serieznyi commented
> Sort the config in the options in reverse order, so the latest version number is directly below the `latest` tag.
> 
> When setting the option to `Latest version` and then clicking on ok or reload integration, an error pops up `Error getting current tag. Lualib not downloaded`.
> 
> On first startup i had the crash.
> 
> ```
> java.lang.NullPointerException: Cannot invoke "org.jsoup.nodes.Element.text()" because the return value of "org.jsoup.nodes.Document.selectFirst(String)" is null
> 	at moe.knox.factorio.core.parser.ApiParser.downloadAndParseAPI(ApiParser.java:687)
> 	at moe.knox.factorio.core.parser.ApiParser.assureDir(ApiParser.java:653)
> 	at moe.knox.factorio.core.parser.ApiParser.run(ApiParser.java:127)
> 	at com.intellij.openapi.progress.impl.CoreProgressManager.startTask(CoreProgressManager.java:442)
> 	at com.intellij.openapi.progress.impl.ProgressManagerImpl.startTask(ProgressManagerImpl.java:114)
> 	at com.intellij.openapi.progress.impl.CoreProgressManager.lambda$runProcessWithProgressAsynchronously$5(CoreProgressManager.java:493)
> 	at com.intellij.openapi.progress.impl.ProgressRunner.lambda$submit$3(ProgressRunner.java:252)
> 	at com.intellij.openapi.progress.impl.CoreProgressManager.lambda$runProcess$2(CoreProgressManager.java:188)
> 	at com.intellij.openapi.progress.impl.CoreProgressManager.lambda$executeProcessUnderProgress$12(CoreProgressManager.java:608)
> 	at com.intellij.openapi.progress.impl.CoreProgressManager.registerIndicatorAndRun(CoreProgressManager.java:683)
> 	at com.intellij.openapi.progress.impl.CoreProgressManager.computeUnderProgress(CoreProgressManager.java:639)
> 	at com.intellij.openapi.progress.impl.CoreProgressManager.executeProcessUnderProgress(CoreProgressManager.java:607)
> 	at com.intellij.openapi.progress.impl.ProgressManagerImpl.executeProcessUnderProgress(ProgressManagerImpl.java:60)
> 	at com.intellij.openapi.progress.impl.CoreProgressManager.runProcess(CoreProgressManager.java:175)
> 	at com.intellij.openapi.progress.impl.ProgressRunner.lambda$submit$4(ProgressRunner.java:252)
> 	at java.base/java.util.concurrent.CompletableFuture$AsyncSupply.run(CompletableFuture.java:1768)
> 	at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1136)
> 	at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:635)
> 	at java.base/java.util.concurrent.Executors$PrivilegedThreadFactory$1$1.run(Executors.java:702)
> 	at java.base/java.util.concurrent.Executors$PrivilegedThreadFactory$1$1.run(Executors.java:699)
> 	at java.base/java.security.AccessController.doPrivileged(AccessController.java:399)
> 	at java.base/java.util.concurrent.Executors$PrivilegedThreadFactory$1.run(Executors.java:699)
> 	at java.base/java.lang.Thread.run(Thread.java:833)
> ```
> 
> To reproduce: Select any version and download it, then restart the IDE.
> 
> Also i would recommend to also save `latest` as state, so on every startup it is checked if a new version is available and then automatically downloaded (and not only manually).

It is because `ApiParser` can`t parse html page of 1.1.62 because in new version of api she was changed.

2022-09-14 19:55 UTC, knoxfighter commented on src/main/java/moe/knox/factorio/intellij/FactorioAutocompletionConfig.java
> +    private final FactorioApiVersion latestExistsVersion;
rename to `latestVersion` or `latestExistingVersion` or `latestSupportedVersion`.

2022-09-15 13:28 UTC, merged